# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "The World of Eadwyn"
description:	       "Eadwyn is a visionary world where nature, technology, and humanity evolve as one. Explore the fusion of regenerative design, decentralized systems, and storytelling that reimagines how we live, build, and connect — from living architecture to the EAD Coin, the currency of regeneration."
author:              "Eadwyn"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
